import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import TopBar from "./components/TopBar";
import GlyphCarousel from "./components/GlyphCarousel";
import ProjectSummary from "./components/ProjectSummary";
import { ViewModeProvider } from "./context/ViewModeContext";
import { ActiveProjectProvider } from "./context/ActiveProjectContext";
import MainColumn from "./components/MainColumn";
import CaseStudyContent from "./components/CaseStudyContent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >
        <ActiveProjectProvider>
          <ViewModeProvider>
            <TopBar />
            <main className="relative flex w-screen bg-gray-200">
              <div className="flex-1 flex h-screen flex-col justify-center overflow-hidden bg-red-50">
                <GlyphCarousel />
              </div>
              <MainColumn>
                <ProjectSummary />
                <CaseStudyContent />
                {children}
              </MainColumn>
              <div className="flex-1 bg-yellow-200"></div>
            </main>
          </ViewModeProvider>
        </ActiveProjectProvider>
      </body>
    </html>
  );
}
