import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ViewModeProvider } from "./context/ViewModeContext";
import { ActiveProjectProvider } from "./context/ActiveProjectContext";
import MainColumn from "./components/MainColumn";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden overscroll-none touch-none bg-background text-foreground h-full`}
      >
        <ActiveProjectProvider>
          <ViewModeProvider>
            <MainColumn>{children}</MainColumn>
          </ViewModeProvider>
        </ActiveProjectProvider>
      </body>
    </html>
  );
}
