export const HEADER_STICKY_RUNWAY_PX = 240;
export const HEADER_PANE_NAV_MORPH_TRIGGER_PX = 8;
export const HEADER_PANE_NAV_REVERSE_OFFSET_PX = 1;
export const HEADER_BOTTOM_CLEARANCE_MOBILE_PX = 50;
export const HEADER_BOTTOM_CLEARANCE_DESKTOP_PX = 70;
export const HEADER_IMAGE_BOTTOM_GAP_PX = 16;

export const HEADER_PANE_NAV_CONTENT_FADE_MS = 50;
export const HEADER_PANE_NAV_MORPH_MS = 150;
export const HEADER_PANE_NAV_DESTINATION_FADE_MS = 50;
export const HEADER_PANE_NAV_REVERSE_DELAY_MS = 150;
