export const HEADER_INTRO_DISTANCE_LVH = 100;

export const HEADER_PANE_NAV_MORPH_PROGRESS = 0.15;
export const HEADER_IMAGE_FADE_START_PROGRESS = 0.5;

export const HEADER_PANE_NAV_CONTENT_FADE_MS = 50;
export const HEADER_PANE_NAV_MORPH_MS = 150;
export const HEADER_PANE_NAV_DESTINATION_FADE_MS = 50;

export const BOTTOM_CARD_REVEAL_START_DISTANCE_VH = 50;
export const BOTTOM_CARD_REVEAL_END_DISTANCE_PX = 100;

export const HEADER_CONTENT_START_LVH =
  100 + HEADER_INTRO_DISTANCE_LVH * HEADER_IMAGE_FADE_START_PROGRESS;
