export const HEADER_STICKY_RUNWAY_PX = 120;
export const HEADER_PANE_NAV_MORPH_TRIGGER_PX = 8;
export const HEADER_PANE_NAV_REVERSE_OFFSET_PX = 1;

export const HEADER_PANE_NAV_CONTENT_FADE_MS = 50;
export const HEADER_PANE_NAV_MORPH_MS = 150;
export const HEADER_PANE_NAV_DESTINATION_FADE_MS = 50;
