export const HEADER_INTRO_DISTANCE_SVH = 100;
export const HEADER_PANE_END_PROGRESS = 0.25;
export const HEADER_IMAGE_FADE_START_PROGRESS = 0.375;

export const HEADER_CONTENT_START_SVH =
  100 + HEADER_INTRO_DISTANCE_SVH * HEADER_IMAGE_FADE_START_PROGRESS;
